# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c20d8ac27300ff466748c8be5fe14edb"
name = "advanced-discounts"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,read_products"

[webhooks]
api_version = "2026-10"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
